merchq/mercs/gm/urls.py
# -*- coding: utf-8 -*-

#   Copyright 2013 Tuukka Turto
#
#   This file is part of unexpected-raptor.
#
#   unexpected-raptor is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   unexpected-raptor is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with unexpected-raptor.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, url

from mercs.gm import views

urlpatterns = patterns('',
    url(r'^$',
        views.index,
        name='mercs.gm.index'),
    url(r'^log/$',
        views.gm_log,
        name='mercs.gm.log'),
    url(r'^log/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$',
        views.gm_log,
        name='mercs.gm.log.archive'),
    url(r'^cycle/$',
        views.gm_cycle,
        name='mercs.gm.cycle_action'),
    url(r'^log_entries/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$',
        views.log_entries,
        name='mercs.gm.log_entries'),
    url(r'^log_entries/$',
        views.log_entries,
        name='mercs.gm.log_entries'),
)

merchq/mercs/personnel/urls.py
# -*- coding: utf-8 -*-

#   Copyright 2013 Tuukka Turto
#
#   This file is part of unexpected-raptor.
#
#   unexpected-raptor is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   unexpected-raptor is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with unexpected-raptor.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import patterns, url

from mercs.personnel import views

urlpatterns = patterns('',
    url(r'^$',
        views.index,
        name='mercs.personnel.index'),
    url(r'^(?P<force_id>\d+)/$',
        views.force_personnel,
        name='mercs.personnel.force'),
    url(r'^person/(?P<person_id>\d+)/$',
        views.person_details,
        name='mercs.personnel.person'),
)

merchq/mercs/personnel/models.py
# -*- coding: utf-8 -*-

#   Copyright 2013 Tuukka Turto
#
#   This file is part of unexpected-raptor.
#
#   unexpected-raptor is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   unexpected-raptor is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with unexpected-raptor.  If not, see <http://www.gnu.org/licenses/>.

from django.db import models
import mercs.forces.models
from mercs.armoury.models import Vehicle
from mercs.astrography.models import Planet

class Position(models.Model):
    position_name = models.CharField(max_length = 100)
    base_salary = models.IntegerField(default = 0)

    def __unicode__(self):
        return self.position_name

class SkillDefinition(models.Model):
    skill_name = models.CharField(max_length = 50)

    def __unicode__(self):
        return self.skill_name

class SkillLevel(models.Model):
    level_name = models.CharField(max_length = 25)
    salary_multiplier = models.FloatField(default = 1.0)

    def __unicode__(self):
        return self.level_name

class Rank(models.Model):
    rank_name = models.CharField(max_length = 25)
    salary_multiplier = models.FloatField(default = 1.0)

    def __unicode__(self):
        return self.rank_name

class Team(models.Model):
    
    team_name = models.CharField(max_length = 100)

    vehicle = models.ForeignKey(Vehicle,
                                blank = True,
                                null = True)

    def location(self):
        locations = set([person.location for person in self.person_set.all()])

        if len(locations) == 1:
            return locations.pop()
        else:
            return None

    def __unicode__(self):
        return self.team_name

class Person(models.Model):
    person_name = models.CharField(max_length = 100)
    position = models.ForeignKey(Position)
    skill_level = models.ForeignKey(SkillLevel)
    rank = models.ForeignKey(Rank)    
    force = models.ForeignKey(mercs.forces.models.Force,
                              null = True,
                              blank = True)
    team = models.ForeignKey(Team,
                             null = True,
                             blank = True)
    location = models.ForeignKey(Planet,
                                 null = True,
                                 blank = True)
    image = models.CharField(max_length = 100)

    def get_salary(self):
        return (self.position.base_salary *
                self.rank.salary_multiplier *
                self.skill_level.salary_multiplier)
    
    def __unicode__(self):
        return '{0} {1} {2} {3}'.format(self.skill_level,
                                        self.position,
                                        self.rank,
                                        self.person_name)

class Skill(models.Model):
    skill_definition = models.ForeignKey(SkillDefinition)
    person = models.ForeignKey(Person)
    skill_score = models.IntegerField(default = 0)

    def __unicode__(self):
        return '{0}-{1}: {2}'.format(self.person.person_name,
                                     self.skill_definition,
                                     self.skill_score)

merchq/mercs/personnel/views.py
# -*- coding: utf-8 -*-

#   Copyright 2013 Tuukka Turto
#
#   This file is part of unexpected-raptor.
#
#   unexpected-raptor is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   unexpected-raptor is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with unexpected-raptor.  If not, see <http://www.gnu.org/licenses/>.

from django.http import HttpResponse
from django.db.models import Count
from django.shortcuts import render, get_object_or_404

from mercs.personnel.models import Person, Position
from mercs.forces.models import Force
from mercs.common.models import Parameter

def index(request):
    forces = Force.objects.all().annotate(personnel_count = Count('person'))
    current_date = Parameter.objects.filter(parameter_name = 'current date')[0].date_value

    context = {'forces': forces,
               'current_date': current_date}

    return render(request, 'personnel/index.html', context)

def force_personnel(request, force_id):
    force = get_object_or_404(Force, id=force_id)
    people = force.person_set.all().order_by('position', 'person_name')
    positions = Position.objects.all().order_by('position_name')
    total_salary = sum([person.get_salary() for person
                        in people])

    pos_data = []

    for position in positions:
        matching_people = [person for person in people
                           if person.position == position]
        pos_data.append([position,
                         matching_people,
                         sum([person.get_salary() for person
                              in matching_people])])
   
    current_date = Parameter.objects.filter(parameter_name = 'current date')[0].date_value

    context = {'force': force,
               'force_personnel': pos_data,
               'total_salary': total_salary,
               'current_date': current_date}

    return render(request, 'personnel/force_personnel.html', context)

def person_details(request, person_id):

    person = get_object_or_404(Person, id=person_id)
    current_date = Parameter.objects.filter(parameter_name = 'current date')[0].date_value

    context = {'person': person,
               'force': person.force,
               'current_date': current_date}

    return render(request, 'personnel/person_details.html', context)

merchq/mercs/personnel/templates/personnel/app_base.html
{% extends "base.html" %}

{% block app_menu %}
<a href="{% url mercs.personnel.index %}">Personnel</a> &nbsp; &nbsp; &nbsp; &nbsp;

{% if force %}
<a href="{% url mercs.personnel.force force.id %}">{{force.force_name}}</a> &nbsp; &nbsp; &nbsp; &nbsp;
{% endif %}

{% if person %}
<a href="{% url mercs.personnel.person person.id %}">{{person.person_name}}</a> &nbsp; &nbsp; &nbsp; &nbsp;
{% endif %}

{% endblock %}

merchq/mercs/personnel/templates/personnel/force_personnel.html
{% extends "personnel/app_base.html" %}

{% block content %}

<table cellpadding="4">
<tr>
  <th>Position</th>
  <th>Name</th>  
  <th>Skill level</th>
  <th>Rank</th>
  <th>Salary</th>
  <th>Team</th>
  <th>Location</th>
</tr>

{% for entry in force_personnel %}

  <tr>
    <td>{{ entry.0 }}</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>

  {% for person in entry.1 %}
    <tr>
      <td></td>
      <td><a href="{% url mercs.personnel.person person.id %}">{{ person.person_name }}</a></td>
      <td>{{ person.skill_level }}</td>
      <td>{{ person.rank }}</td>
      <td>{{ person.get_salary }}</td>
      <td><a href="">{{ person.team.team_name }}</a></td>
      {% if person.location %}
        <td><a href="{% url mercs.astrography.planet person.location.id %}">{{ person.location.name }}</a></td>
      {% else %}
        <td></td>
      {% endif %}
    </tr>

  {% endfor %}

  <tr>
    <td colspan="3"></td>
    <td>Sub-Total</td>
    <td>{{ entry.2 }}</td>
    <td></td>
    <td></td>
  </tr>

{% endfor %}

  <tr>
    <td colspan="3"></td>
    <td>Total</td>
    <td>{{ total_salary }}</td>
    <td></td>
    <td></td>
  </tr>

</table>

{% endblock %}

merchq/mercs/personnel/templates/personnel/index.html
{% extends "personnel/app_base.html" %}

{% block content %}
{% if forces %}
    <table>
    <tr>
      <th>Force</th>
      <th>Personnel count</th>
    </tr>
    {% for force in forces %}
        <tr>
          <td><a href="{% url mercs.personnel.force force.id %}">{{ force.force_name }}</a></td>
          <td>{{ force.personnel_count }}</td>
        </tr>
    {% endfor %}

    </table>
{% else %}
    <p>No forces available.</p>
{% endif %}
{% endblock %}

merchq/mercs/personnel/templates/personnel/person_details.html
{% extends "personnel/app_base.html" %}

{% block content %}

<div id="main_sub">
<table>
<tr>
  <th></th>
  <th></th>
</tr>

<tr>
  <td>Name:</td>
  <td>{{ person.person_name }}</td>
</tr>
<tr>
  <td>Position:</td>
  <td>{{ person.position }}</td>
</tr>
<tr>
  <td>Skill level:</td>
  <td>{{ person.skill_level }}</td>
</tr>

{% for skill in person.skill_set.all %}
  <tr>
    <td>{{ skill.skill_definition.skill_name }}:</td>
    <td>{{ skill.skill_score }}</td>
  </tr>
{% endfor %}

<tr>
  <td>Rank:</td>
  <td>{{ person.rank }}</td>
</tr>
<tr>
  <td>Salary:</td>
  <td>{{ person.get_salary }}</td>
</tr>
<tr>
  <td>Team:</td>
  <td><a href="">{{ person.team.team_name }}</a></td>
</tr>
<tr>
  <td>Location:</td>
  {% if person.location %}
    <td><a href="{% url mercs.astrography.planet person.location.id %}">{{ person.location.name }}</a></td>
  {% else %}
    <td></td>
  {% endif %}
</tr>
</table>
</div>

<div id="main_sub">
<img src="/media/{{person.image}}" alt="{{person.person_name}}">
</div>

<div id="clear_float"></div>

{% endblock %}

{% block sidebar %}
<a href="">Fire</a><br>
<a href="">Promote</a><br>
{% endblock %}